---
title: "Final Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sp)
library(maps)
library (ggplot2)
library (chron)
library(plyr)
library(scales)
library(zoo)
library(lattice)
library(RColorBrewer)
library(reshape2)
library(latticeExtra)
```

## R Markdown

Project Area Location

```{r cars}
map('county', 'ohio') # plot county boundaries for all of Ohio
map('county', 'ohio,madison', add=T, fill = T, col="purple") #add Madison County, Ohio in purple to map
map.text("county", "ohio,Madison", add=T) #add text to madison

#Kokomo <- Sys.glob("C:/workspace/merge71/*.csv") #finds all csv files in folder
#for (Ko in Kokomo) {Kokomo71 <- read.csv(Ko, header = TRUE, sep = ",")} #iterate across all files?
Kokomo71=ldply(list.files(path="C:/workspace/merge71/",pattern="csv",full.names=TRUE),function(filename) {
  dum=read.csv(filename)
  dum$filename=filename
  return(dum)
})

Kokomo71$date <- as.Date (Kokomo71$date, '%m/%d/%Y')

ggplot(data=Kokomo71, aes (date, feet)) +geom_line(colour='purple')+ ylim(10, -5) #plot line

```

**Objectives:**

* Show multiple years of data from one data logger site
* Organize data
* Data Gaps
* Use R instead of excel to create graphs
* Create Plots
  * Totals by months and years
  * Averages by Month and years
  * Show a week of all depths
* Create output report using R Markdown

**Plots:**

```{r pressure, echo=TRUE}
Kokomo71$inches <-(Kokomo71$feet*12) #feet x inches
Kokomo71$convin <- (Kokomo71$inches-21) #inches - 21
Kokomo71$cm <- (Kokomo71$convin*2.54) #converted inches x centimeters

cmavmonths <- aggregate(cm ~ month+year, data = Kokomo71, mean) #averages of months & years

Kokomo71$date<-as.POSIXlt(Kokomo71$date,format="%m/%d/%y %H:%M:%S")
Kokomo71 <- within(Kokomo71, {
                      day =   as.character(format(Kokomo71$date, "%m/%d/%y"))
                      Jday =  as.integer(format(Kokomo71$date, "%j"))
                      year =  as.integer(format(Kokomo71$date, "%Y"))
                      month = as.integer(format(Kokomo71$date, "%m"))
                      week =  as.integer(format(Kokomo71$date, "%W"))
                      })

#plot averages of months and years
ggplot(data = cmavmonths, aes(year, cm)) +geom_line(colour="purple")+geom_smooth(colour="green")+ ylim(250, -75)

#plot data
xyplot(cm ~ year | week, data=Kokomo71_month6, main='Water Table', type=c('l', 'g'), as.table=TRUE, layout=c(2,6), xlab='week', ylab='cm')

#plot data gaps
levelplot(factor(!is.na(cm)) ~ month * factor(year) | year, main='Water Table',
          data=Kokomo71, layout=c(2,6), col.regions=c('grey', 'purple'), cuts=2, 
          colorkey=FALSE, as.table=TRUE, scales=list(alternating=3, cex=1), 
          par.strip.text=list(cex=0.85), strip=strip.custom(bg='yellow'), 
          xlab='month', ylab='year')




```


